version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Serkan1234
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  consume:
    image: ${DOCKER_REGISTRY-}consume
    build:
      context: .
      dockerfile: Consume/Dockerfile
    ports:
      - "5100:5000"
      - "5101:5001"

volumes:
  mssql-data:
